name: "Pytest"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:
  
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.9"]
  
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry pytest
            poetry export -f requirements.txt --output requirements.txt
            pip install -r requirements.txt
        - name: Setup AWS Credentials
          run: |
            touch ~/.aws/credentials
            echo "[default]" >> ~/.aws/credentials
            echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
            echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY}}" >> ~/.aws/credentials

        - name: Test with Pytest
          run: |
            pytest -v --junitxml=junit-report.xml